부산대 12조 FE 6주차 PR
kakao-tech-campus-2nd-step3/Team12_FE pull request #25
Opened 2024-10-11 09:06 UTC by cla6shade

안녕하세요 멘토님! 6주차 PR로 인사드립니다.

## 금주에 한 일

금주에는 로그인 UI, 메인 화면의 스터디 리스트 섹션의 UI를 구현했고, 기초 컴포넌트를 약간 수정하여 사용성을 높였습니다.

![image](https://github.com/user-attachments/assets/0717a15f-2fee-4ab2-85cd-1f4670aabc0a)
![image](https://github.com/user-attachments/assets/1799e39d-0d5d-4e74-ad30-3d79d6db99b9)
![image](https://github.com/user-attachments/assets/57fd5d86-7ce2-4250-a33b-bb5cbea20c06)

특히 지난주 PR(#19)에서 `백엔드와의 협업에서 소통해야될 사항`에 대해 조언해주신 내용이 큰 도움이 되었습니다. 다음 주차에 구현할 기능과 이번주에 한 일 등을 공유하며 같은 방향을 바라보도록 의견을 정돈할 수 있었습니다!

## 리뷰받고 싶은 내용

1. Modal 관련 (이민경님 질문)

현재 모달은 모두 고정 너비와 높이 를 갖는데, 반응형으로 기기 크기에 따라 UI가 변화하도록 수정하려고 하는데, 어떤 식으로 수정할 수 있는지 조언을 얻고 싶습니다!

2. eslint, prettier 등 코드 컨벤션 관리 도구 관련

eslint는 컨벤션과 관련된 코드 문제점 감지, prettier은 코드 포맷팅에 사용하는 도구로서 함께 사용한다는 글을 꽤 많이 접했습니다. 하지만 `코드 포맷팅은 eslint --fix 명령어로도 가능한데 굳이 prettier을 사용해야 할까?`라는 의문이 들게 되었습니다.

비슷한 맥락에서, 현재 프로젝트의 팀원 모두가 IDE에 내장된 run on save 기능을 이용하여 코드가 자동으로 컨벤션에 맞춰 수정되도록 하고 있어서 코드 컨벤션 관리에 크게 어려움이 없는데, prettier, husky와 같은 도구를 도입하지 않았을 때 발생할 수 있는 문제점이나, 이런 도구들을 도입했을 때 `run on save`에 비해 갖는 장점이 궁금합니다.

항상 시간내어 리뷰해주셔서 감사드립니다! 이번 주차도 잘 부탁드립니다.

2024-10-12 02:34 UTC, taehwanno requested changes
고생하셨습니다. 피드백 드려요!

2024-10-12 02:34 UTC, taehwanno commented on src/features/modal/studyCreation/StudyCreation.styles.ts
> +    avatarStyle, selectPhotoButtonStyle, creationButtonStyle, textStyle,
`useStudyCreationStyle`는 서로 같이 수정될 가능성이 떨어지는 연관성이 없는 스타일이 우발적으로 한 곳에서 모여서 관리되는거 같아요. Avatar, SelectPhotoButton, CreationButton, Text가 각자 수정돈다고 해서 나머지 다른 곳에 영향을 주는 가능성이 낮아보인다는거죠.

재사용 가능한 UI의 단위를 지금처럼 훅으로 공유하기 보다는 컴포넌트로 적용될 수 있게 리팩토링 하는게 좋겠습니다. 예를 들어, 34번 라인의 avaterStyle이 `Avatar` 컴포넌트에서 특정 UI에서만 적용돼야한다면 기존의 `Avatar` 컴포넌트 내부에서 관리하고 props로 `bordered`와 같은 속성을 추가해서 적용하는 방법이 있을 거 같네요.

```tsx
<Avatar bordered />
```

다른 방향으로는 Avatar에서 스타일링을 외부에서 수정할 수 있게 css를 여전히 props로 전달하고 싶다면 Avater를 감싸고 해당 스타일을 css props로 직접 내려주는 새로운 컴포넌트를 만들어서 사용하면 되겠죠.

```tsx
<BorderedAvatar />
```

코드 전반적으로 UI를 구성하는 최소 단위는 스타일 시트가 아니라 컴포넌트일 수 있게 개선해보면 좋겠습니다.

2024-10-12 02:34 UTC, taehwanno commented on src/features/modal/studyCreation/StudyCreationModal.tsx
> +    <DefaultPaddedContainer>
`Modal` 안에서 portal을 사용하고 있기 때문에 `Modal`을 포함해서 자손 컴포넌트는 `DefaultPaddedContainer` 스타일링에 영향을 받지 않을 거 같은데 한번 확인해보시겠어요?

2024-10-12 04:22 UTC, harugi7 commented
피드백 감사합니다! 열심히 반영해보겠습니다!

2024-10-12 13:05 UTC, mingkyeongg commented on src/features/modal/studyCreation/StudyCreation.styles.ts
> +    avatarStyle, selectPhotoButtonStyle, creationButtonStyle, textStyle,
안녕하세요 멘토님! 다양한 개선방법을 알려주셔서 감사합니다!😊

Avatar에 bordered 속성을 주는 것으로 변경하였습니다. Text나 ButtonStyle에도 중복 부분이 있어 다음주 PR에 이 부분 좀 더 개선해보도록 하겠습니다!

2024-10-12 13:10 UTC, mingkyeongg commented on src/features/modal/studyCreation/StudyCreationModal.tsx
> +    <DefaultPaddedContainer>
React Portal의 동작 방식을 확인해 보니, 모달을 호출하는 순간 해당 모달이 DOM 트리 상에서 modal-root로 이동하여 상위 컴포넌트의 스타일이 적용되지 않는 것을 확인했습니다. Modal 컨테이너에서 기본 패딩 값을 설정하는 것으로 변경했습니다!

2024-10-13 05:51 UTC, cla6shade commented on package.json
> +  "name": "ditto-frontend",
아하, 서로 다른 환경에서도 동일한 코드 컨벤션을 유지하는데에 도움이 된다고 이해했습니다.
잘 공감되지 않는 부분이었는데 첨부해주신 문서와 멘토님 답변을 통해 이해할 수 있었습니다. 감사합니다!

2024-10-14 14:12 UTC, taehwanno approved these changes
고생하셨습니다!

2024-10-16 00:53 UTC, merged