harugi7 7주차 구현
kakao-tech-campus-2nd-step3/Team12_FE pull request #26
Opened 2024-10-11 10:21 UTC by harugi7

- [x] 헤더 구현
- [ ] 푸터 구현
- [ ] 배너 구현

2024-10-14 12:28 UTC, cla6shade requested changes

2024-10-15 06:38 UTC, harugi7 commented on src/components/header/index.tsx
> +        cssOverride={css`gap: 50px;`}
네 수정했습니다!

2024-10-15 06:43 UTC, harugi7 commented on src/components/header/index.tsx
> +          <Avatar
넵! medium은 너무 커서 small size로 수정하였습니다~!

2024-10-15 06:43 UTC, harugi7 commented on src/components/header/index.tsx
> +      cssOverride={css`box-shadow: 0 4px 7px rgba(0, 0, 0, 0.2); position: relative;`}
사이즈 수정하였고, fixed는 한번 고민해봅시다!👍

2024-10-15 07:10 UTC, harugi7 commented on src/components/header/index.tsx
> +                position: absolute;
전부 별도의 모듈로 빼지 않고, footer의 반복적으로 사용되는 div만 분리해보았습니다.
확실히 코드가 깔끔해지네요!
혹시 현재는 반복되지않더라도 cssOverride 부분을 전부 별도의 모듈로 빼는것이 좋을까요? 
의견 궁금합니다!

2024-10-16 00:28 UTC, cla6shade commented on src/components/header/index.tsx
> +                position: absolute;
저는 보통 전부다 빼진 않고, & 선택자나 미디어 쿼리 등으로 인해 스타일시트가 지나치게 길어져서 UI 구조 파악에 어려움이 생기는 경우 빼서 사용하는 편입니다!

그리고 스타일시트 상수를 별도의 모듈로 빼지 않고도 가독성이 아주 조금 나아지는 방법이 있는데, cssOverride prop으로 스타일시트를 `객체 형태`로 전달하는 것입니다.

cssOverride prop은 emotion의 CSSObject 타입으로, ` css`` `와 같은 `tagged template literal`을 전달받을 수 있지만, 객체 형태의 스타일도 전달받을 수 있어요. [이 링크](https://emotion.sh/docs/object-styles)를 참조해보시면 좋을 것 같습니다.

근데 어차피 길어지면 둘다 복잡한건 마찬가지라, `스타일시트가 지나치게 길어져서 UI 구조파악이 어려울경우 빼면 좋을 것 같다`는 것이 제 의견입니다.

2024-10-16 00:52 UTC, cla6shade requested changes

2024-10-16 00:52 UTC, cla6shade commented on src/components/iceBreaking/index.tsx
> +
현재 프로젝트 구조상 components/iceBreaking 보다는 feature/main/iceBreaking에 위치시키는게 조금 더 자연스럽지 않을까요?

초기에 생각했던 프로젝트 구조와 현재의 방향을 종합해보면 아래와 같이 정리해볼 수 있을 것 같습니다.

1. 메인 화면에만 표시되는 컴포넌트 -> features/main/기능 구분 (ex. 메인에만 표시될 배너: features/main/banner)
2. 화면이나 기능 구별 없이 아무데서나 쓸 수 있는 컴포넌트 -> components/ 하위에 배치
3. 특정 화면에만 표시되는 건 아닌데 특정한 기능을 담당하고 있는 컴포넌트 -> features/기능명 하위에 배치

components
- 공통적으로 사용될 수 있는 컴포넌트 모음
features
- 화면이름 (main)
  - 해당 화면에 들어갈 기능/컴포넌트 (banner, studyList 등)
- 기능이름 (ex. login)
  - 해당하는 기능을 담당하거나 관련된 기능을 담당하는 컴포넌트 (ex. LoginForm)

2024-10-16 00:52 UTC, cla6shade commented on src/components/ranking/index.tsx
> +
위의 banner과 동일하게 위치에 대해 한 번 고민해보시면 좋을 것 같습니다!

2024-10-17 05:12 UTC, harugi7 commented on src/components/iceBreaking/index.tsx
> +
넵 그 편이 더 자연스러울 것 같네요~! 수정하였습니다!

2024-10-17 05:18 UTC, harugi7 commented on src/components/ranking/index.tsx
> +
넵 이 경로도 수정하였습니다!

2024-10-17 06:20 UTC, cla6shade approved these changes
고생하셨습니다!

2024-10-17 06:21 UTC, merged