PersonalInfoModal Validation, 테스트 코드
kakao-tech-campus-2nd-step3/Team12_FE pull request #41
Opened 2024-10-23 13:40 UTC by mingkyeongg

# 변경점 👍
PersonalInfoModal form validation과 테스트 코드를 작성하였습니다.
CheckBox 컴포넌트에 ref 지원이 가능하도록 추가하였습니다.

### Validation
- 모든 입력 칸이 비어있지 않고 약관 동의 checkbox를 눌러야 버튼이 활성화 됩니다.
- 닉네임은 3~10자의 한글, 숫자, 영어만 가능합니다.
- 이메일은 example@mail 형식을 지켜야합니다.
- 전화번호는 010-0000-0000 형식을 지켜야 합니다.
- 자기소개는 255자 이하만 입력 가능합니다.
 
### 테스트 코드
- 모든 input이 올바를때 버튼이 활성화 되는지
- 이메일, 전화번호 오류 메시지가 잘 출력되는지
두 가지 케이스 작성하였습니다.
 
# 리팩토링 🛠
- input placeholder를 입력 형식을 지킬 수 있도록 예시 문구로 변경하였습니다.
 
# 스크린샷 🖼

## 에러 버전
<img width="385" alt="스크린샷 2024-10-23 오후 10 31 21" src="https://github.com/user-attachments/assets/7c5f803c-201e-427d-a1b4-3eec4632da4f">

## 정상 입력 시 버튼 활성화
<img width="395" alt="스크린샷 2024-10-23 오후 10 31 49" src="https://github.com/user-attachments/assets/9294e123-1cc3-4f61-bb59-9166d7efe259">
 
# 비고 ✏
최초에는 아무런 에러가 뜨지 않고 입력이 시작되어야 오류 메시지가 나타나는데 최초에도 오류 메시지가 나오게 하면 좋을까요?

저는 최초에는 없는게 좋을 것 같은데 어떻게 생각하시는지 궁금합니다!

2024-10-23 16:29 UTC, cla6shade requested changes

2024-10-23 16:29 UTC, cla6shade commented on src/features/modal/studyCreation/tests/InviteToStudy.stories.tsx
> +  title: 'Features/Modal/StudyCreation/Tests/InviteToStudyModal',
삭제하신 후 스토리명도 원래대로 돌려주세요~

2024-10-23 16:29 UTC, cla6shade commented
고생하셨습니다!! 몇가지 마이너한 부분만 수정하면 더 좋을것같습니다!

2024-10-28 00:16 UTC, cla6shade commented
p1; 컨플릭트 한 번 해결해주시고, Paragraph, ErrorText의 변경된 사용법을 반영해주세요~ 고생하셨습니다!

2024-10-28 06:28 UTC, mingkyeongg commented
말씀주셨던 개선사항 반영하였습니다! 
- personalInfo -> Member 이름 변경
- 중복된 storybook 파일 제거
- 충돌 해결, paragraph 변경된 사용법 반영

2024-10-30 13:40 UTC, merged